server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: ALWAYS

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  profiles:
    active: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable:
          idempotence: true

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    jdbc.sqltiming: TRACE
