server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 2
      connection-test-query: select 1
      connection-timeout: 5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/point?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: a90a1027a
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: point
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest # latest, earliest, none
    listener:
      ack-mode: manual

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    jdbc.sqltiming: TRACE
